# Autogenerated wrapper script for Packmol_jll for armv7l-linux-gnueabihf-libgfortran4
export packmol

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Packmol")
JLLWrappers.@declare_executable_product(packmol)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        packmol,
        "bin/packmol",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
